In [12]:
import pandas as pd
import seaborn as sns

In [13]:
data = pd.read_csv('../train_delay/All Delays 2018-19.csv')
data

,FINANCIAL_YEAR_AND_PERIOD,ORIGIN_DEPARTURE_DATE,TRUST_TRAIN_ID_AFFECTED,PLANNED_ORIG_LOC_CODE_AFF,PLANNED_ORIG_GBTT_DATETIME_AFF,PLANNED_ORIG_WTT_DATETIME_AFF,PLANNED_DEST_LOC_CODE_AFFECTED,PLANNED_DEST_GBTT_DATETIME_AFF,PLANNED_DEST_WTT_DATETIME_AFF,TRAIN_SERVICE_CODE_AFFECTED,...,INCIDENT_DESCRIPTION,REACTIONARY_REASON_CODE,INCIDENT_RESPONSIBLE_TRAIN,PERFORMANCE_EVENT_CODE,START_STANOX,END_STANOX,EVENT_DATETIME,PFPI_MINUTES,TRUST_TRAIN_ID_RESP,TRUST_TRAIN_ID_REACT
0,2018/19_P01,01-APR-18,011B44MN01,1100,01-APR-2018 13:30,01-APR-2018 13:30,4303,01-APR-2018 16:50,01-APR-2018 16:50,23549003.0,...,1H45 LOST PTH DLW,YE,1H45,M,1100,1144,01-APR-2018 14:12,6.0,041H45MF01,061H09MI01
1,2018/19_P01,01-APR-18,011E17MF01,1100,01-APR-2018 09:40,01-APR-2018 09:40,54311,01-APR-2018 17:51,01-APR-2018 17:51,21701001.0,...,YRK AU TC FLR,YP,NaN,M,16005,16421,01-APR-2018 16:02,7.0,NaN,041E97MM01
2,2018/19_P01,01-APR-18,011M16MZ01,1100,01-APR-2018 20:26,01-APR-2018 20:26,72410,02-APR-2018 09:17,02-APR-2018 09:15,23558003.0,...,1M11 LOSS OF POWER GLQ LNZ,YD,NaN,M,4303,4303,02-APR-2018 01:58,50.0,NaN,061M11M701
3,2018/19_P01,01-APR-18,011M16MZ01,1100,01-APR-2018 20:26,01-APR-2018 20:26,72410,02-APR-2018 09:17,02-APR-2018 09:15,23558003.0,...,1M16 OVERTIME NCL,NaN,1M16,M,12931,12931,02-APR-2018 03:43,3.0,011M16MZ01,NaN
4,2018/19_P01,01-APR-18,011T80ML01,1100,01-APR-2018 12:44,01-APR-2018 12:44,6401,01-APR-2018 15:58,01-APR-2018 15:58,23549003.0,...,1H45 LOST PTH DLW,YE,1H45,M,1100,1144,01-APR-2018 13:31,7.0,041H45MF01,041H45MF01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490313,2018/19_P01,28-APR-18,894Y19CK28,89391,NaN,28-APR-2018 12:02,86607,NaN,28-APR-2018 16:32,51462781.0,...,4Y19 LOST 3 CLJ-BNS,NaN,894Y19CK28,M,87219,87149,28-APR-2018 13:50,1.5,894Y19CK28,NaN
490314,2018/19_P01,28-APR-18,894Y19CK28,89391,NaN,28-APR-2018 12:02,86607,NaN,28-APR-2018 16:32,51462781.0,...,4Y19 LOCO FLR WOK-FNB,NaN,894Y19CK28,M,86069,86083,28-APR-2018 16:50,11.0,894Y19CK28,NaN
490315,2018/19_P01,28-APR-18,895C542Y28,89004,NaN,28-APR-2018 19:30,89427,NaN,28-APR-2018 21:15,24648004.0,...,CHX KENT ECS 28 04 18,NaN,NaN,M,89611,89611,28-APR-2018 20:48,0.0,NaN,NaN
490316,2018/19_P01,28-APR-18,895H74MF28,89377,NaN,28-APR-2018 09:45,89375,NaN,28-APR-2018 09:48,24602004.0,...,CHX KENT ECS 28 04 18,NaN,NaN,M,89377,89375,28-APR-2018 09:51,0.0,NaN,NaN
490317,2018/19_P01,28-APR-18,895Q57CU28,89472,NaN,28-APR-2018 17:13,57442,NaN,29-APR-2018 01:43,56661501.0,...,PLANNED CANCELLATION 28/04/18,PD,NaN,S,89472,89472,28-APR-2018 17:13,0.0,NaN,NaN

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490318 entries, 0 to 490317
Data columns (total 39 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   FINANCIAL_YEAR_AND_PERIOD       490318 non-null  object
 1   ORIGIN_DEPARTURE_DATE           490318 non-null  object
 2   TRUST_TRAIN_ID_AFFECTED         490318 non-null  object
 3   PLANNED_ORIG_LOC_CODE_AFF       490318 non-null  int64
 4   PLANNED_ORIG_GBTT_DATETIME_AFF  366415 non-null  object
 5   PLANNED_ORIG_WTT_DATETIME_AFF   490318 non-null  object
 6   PLANNED_DEST_LOC_CODE_AFFECTED  490318 non-null  int64
 7   PLANNED_DEST_GBTT_DATETIME_AFF  366415 non-null  object
 8   PLANNED_DEST_WTT_DATETIME_AFF   490318 non-null  object
 9   TRAIN_SERVICE_CODE_AFFECTED     490291 non-null  float64
 10  SERVICE_GROUP_CODE_AFFECTED     490291 non-null  object
 11  OPERATOR_AFFECTED               490291 non-null  object
 12  ENGLISH_DAY_TYPE                490318 non-null  object
 13  APP_TIMETABLE_FLAG_AFF          490318 non-null  object
 14  TRAIN_SCHEDULE_TYPE_AFFECTED    490318 non-null  object
 15  TRACTION_TYPE_AFFECTED          485188 non-null  object
 16  TRAILING_LOAD_AFFECTED          56039 non-null   float64
 17  TIMING_LOAD_AFFECTED            132349 non-null  object
 18  UNIT_CLASS_AFFECTED             89026 non-null   float64
 19  INCIDENT_NUMBER                 490318 non-null  int64
 20  INCIDENT_CREATE_DATE            490318 non-null  object
 21  INCIDENT_START_DATETIME         490318 non-null  object
 22  INCIDENT_END_DATETIME           490318 non-null  object
 23  SECTION_CODE                    490318 non-null  object
 24  NETWORK_RAIL_LOCATION_MANAGER   490318 non-null  object
 25  RESPONSIBLE_MANAGER             490318 non-null  object
 26  INCIDENT_REASON                 489939 non-null  object
 27  ATTRIBUTION_STATUS              490318 non-null  object
 28  INCIDENT_EQUIPMENT              247771 non-null  object
 29  INCIDENT_DESCRIPTION            490318 non-null  object
 30  REACTIONARY_REASON_CODE         300008 non-null  object
 31  INCIDENT_RESPONSIBLE_TRAIN      224342 non-null  object
 32  PERFORMANCE_EVENT_CODE          490318 non-null  object
 33  START_STANOX                    490318 non-null  int64
 34  END_STANOX                      490318 non-null  int64
 35  EVENT_DATETIME                  490318 non-null  object
 36  PFPI_MINUTES                    490318 non-null  float64
 37  TRUST_TRAIN_ID_RESP             209564 non-null  object
 38  TRUST_TRAIN_ID_REACT            207675 non-null  object
dtypes: float64(4), int64(5), object(30)
memory usage: 145.9+ MB

In [15]:
data.isnull().sum(axis = 0)

FINANCIAL_YEAR_AND_PERIOD              0
ORIGIN_DEPARTURE_DATE                  0
TRUST_TRAIN_ID_AFFECTED                0
PLANNED_ORIG_LOC_CODE_AFF              0
PLANNED_ORIG_GBTT_DATETIME_AFF    123903
PLANNED_ORIG_WTT_DATETIME_AFF          0
PLANNED_DEST_LOC_CODE_AFFECTED         0
PLANNED_DEST_GBTT_DATETIME_AFF    123903
PLANNED_DEST_WTT_DATETIME_AFF          0
TRAIN_SERVICE_CODE_AFFECTED           27
SERVICE_GROUP_CODE_AFFECTED           27
OPERATOR_AFFECTED                     27
ENGLISH_DAY_TYPE                       0
APP_TIMETABLE_FLAG_AFF                 0
TRAIN_SCHEDULE_TYPE_AFFECTED           0
TRACTION_TYPE_AFFECTED              5130
TRAILING_LOAD_AFFECTED            434279
TIMING_LOAD_AFFECTED              357969
UNIT_CLASS_AFFECTED               401292
INCIDENT_NUMBER                        0
INCIDENT_CREATE_DATE                   0
INCIDENT_START_DATETIME                0
INCIDENT_END_DATETIME                  0
SECTION_CODE                           0
NETWORK_RAIL_LOCATION_MANAGER          0
RESPONSIBLE_MANAGER                    0
INCIDENT_REASON                      379
ATTRIBUTION_STATUS                     0
INCIDENT_EQUIPMENT                242547
INCIDENT_DESCRIPTION                   0
REACTIONARY_REASON_CODE           190310
INCIDENT_RESPONSIBLE_TRAIN        265976
PERFORMANCE_EVENT_CODE                 0
START_STANOX                           0
END_STANOX                             0
EVENT_DATETIME                         0
PFPI_MINUTES                           0
TRUST_TRAIN_ID_RESP               280754
TRUST_TRAIN_ID_REACT              282643
dtype: int64